<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(PlatformTargetFrameworks)</TargetFrameworks>
        <Description>ACR UserDialogs Extensions for .NET MAUI</Description>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Acr.UserDialogs</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Acr.UserDialogs\Acr.UserDialogs.csproj" />
    </ItemGroup>
</Project>
