<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net8.0-ios17.0;net8.0-android34.0;net8.0-maccatalyst17.0</TargetFrameworks>
        <Product>$(AssemblyName) ($(TargetFramework))</Product>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(SolutionDir)icon.png" Pack="true" PackagePath="icon.png" />
        <None Include="$(SolutionDir)readme.md" Pack="true" PackagePath="readme.md" />
        <None Include="Platforms\**\*.*" />
        <Compile Remove="Platforms\**\*.*" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('android'))">
        <Compile Include="Platforms\Shared\**\*.cs" />
        <Compile Include="Platforms\Android\**\*.cs" />
        <PackageReference Include="AndHUD" Version="2.1.0" />
        <PackageReference Include="Xamarin.Google.Android.Material" Version="1.9.0.2" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.Contains('ios')) OR $(TargetFramework.Contains('catalyst'))">
        <Compile Include="Platforms\Shared\**\*.cs" />
        <Compile Include="Platforms\ios\**\*.cs" />
        <PackageReference Include="BTProgressHUD" Version="2.2.0" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework.StartsWith('macos'))">
        <Compile Include="Platforms\Shared\**\*.cs" />
        <Compile Include="Platforms\macOS\**\*.cs" />
    </ItemGroup>

    <!--
    <ItemGroup Condition="$(TargetFramework.Contains('windows'))">
        <Compile Include="Platforms\Shared\**\*.cs" />
        <Compile Include="Platforms\Windows\**\*.cs" />
        <Page Include="Platforms\Windows\**\*.xaml" SubType="Designer" Generator="MSBuild:Compile" />
        <Compile Update="Platforms\Windows\**\*.xaml.cs" SubType="Code" DependentUpon="%(Filename)" />  
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.4.240211001" />
    </ItemGroup>
    -->
</Project>