#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Acr.UserDialogs.Resource", IsApplication=false)]

namespace Acr.UserDialogs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f04000a
			public static int backup_country_codes = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int backup_country_names = 2130968587;
			
			// aapt resource value: 0x7f040000
			public static int recurrence_freq = 2130968576;
			
			// aapt resource value: 0x7f040006
			public static int repeat_by_nth_fri = 2130968582;
			
			// aapt resource value: 0x7f040002
			public static int repeat_by_nth_mon = 2130968578;
			
			// aapt resource value: 0x7f040007
			public static int repeat_by_nth_sat = 2130968583;
			
			// aapt resource value: 0x7f040001
			public static int repeat_by_nth_sun = 2130968577;
			
			// aapt resource value: 0x7f040005
			public static int repeat_by_nth_thurs = 2130968581;
			
			// aapt resource value: 0x7f040003
			public static int repeat_by_nth_tues = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int repeat_by_nth_wed = 2130968580;
			
			// aapt resource value: 0x7f040008
			public static int timezone_rename_ids = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int timezone_rename_labels = 2130968585;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010017
			public static int ahBarColor = 2130771991;
			
			// aapt resource value: 0x7f01001f
			public static int ahBarLength = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public static int ahBarWidth = 2130771998;
			
			// aapt resource value: 0x7f01001c
			public static int ahCircleColor = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public static int ahDelayMillis = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public static int ahRadius = 2130771997;
			
			// aapt resource value: 0x7f010018
			public static int ahRimColor = 2130771992;
			
			// aapt resource value: 0x7f010019
			public static int ahRimWidth = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public static int ahSpinSpeed = 2130771994;
			
			// aapt resource value: 0x7f010014
			public static int ahText = 2130771988;
			
			// aapt resource value: 0x7f010015
			public static int ahTextColor = 2130771989;
			
			// aapt resource value: 0x7f010016
			public static int ahTextSize = 2130771990;
			
			// aapt resource value: 0x7f010005
			public static int bpButtonBackground = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int bpCheckIcon = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int bpDeleteIcon = 2130771970;
			
			// aapt resource value: 0x7f010009
			public static int bpDialogBackground = 2130771977;
			
			// aapt resource value: 0x7f010007
			public static int bpDividerColor = 2130771975;
			
			// aapt resource value: 0x7f010004
			public static int bpKeyBackground = 2130771972;
			
			// aapt resource value: 0x7f010008
			public static int bpKeyboardIndicatorColor = 2130771976;
			
			// aapt resource value: 0x7f010000
			public static int bpTextColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int bpTitleColor = 2130771969;
			
			// aapt resource value: 0x7f010006
			public static int bpTitleDividerColor = 2130771974;
			
			// aapt resource value: 0x7f010010
			public static int switchMinWidth = 2130771984;
			
			// aapt resource value: 0x7f010011
			public static int switchPadding = 2130771985;
			
			// aapt resource value: 0x7f010013
			public static int switchPreferenceStyle = 2130771987;
			
			// aapt resource value: 0x7f010012
			public static int switchStyle = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public static int switchTextAppearance = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public static int textOff = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public static int textOn = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public static int thumb = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public static int thumbTextPadding = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public static int track = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050010
			public static int ampm_text_color = 2131034128;
			
			// aapt resource value: 0x7f050015
			public static int blue = 2131034133;
			
			// aapt resource value: 0x7f050016
			public static int blue_focused = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public static int calendar_header = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public static int calendar_selected_date_text = 2131034140;
			
			// aapt resource value: 0x7f05000e
			public static int circle_background = 2131034126;
			
			// aapt resource value: 0x7f050020
			public static int dark_gray = 2131034144;
			
			// aapt resource value: 0x7f050018
			public static int darker_blue = 2131034136;
			
			// aapt resource value: 0x7f050027
			public static int date_picker_selector = 2131034151;
			
			// aapt resource value: 0x7f050019
			public static int date_picker_text_normal = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public static int date_picker_view_animator = 2131034139;
			
			// aapt resource value: 0x7f050028
			public static int date_picker_year_selector = 2131034152;
			
			// aapt resource value: 0x7f050004
			public static int default_button_background_dark = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public static int default_button_background_light = 2131034122;
			
			// aapt resource value: 0x7f050005
			public static int default_button_background_pressed_dark = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public static int default_button_background_pressed_light = 2131034123;
			
			// aapt resource value: 0x7f050003
			public static int default_divider_color_dark = 2131034115;
			
			// aapt resource value: 0x7f050009
			public static int default_divider_color_light = 2131034121;
			
			// aapt resource value: 0x7f050006
			public static int default_keyboard_indicator_color_dark = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public static int default_keyboard_indicator_color_light = 2131034124;
			
			// aapt resource value: 0x7f050001
			public static int default_text_color_holo_dark = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int default_text_color_holo_dark_disabled = 2131034114;
			
			// aapt resource value: 0x7f050007
			public static int default_text_color_holo_light = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int default_text_color_holo_light_disabled = 2131034120;
			
			// aapt resource value: 0x7f050029
			public static int dialog_text_color_holo_dark = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public static int dialog_text_color_holo_light = 2131034154;
			
			// aapt resource value: 0x7f050024
			public static int done_disabled_dark = 2131034148;
			
			// aapt resource value: 0x7f05002b
			public static int done_text_color = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public static int done_text_color_dark = 2131034156;
			
			// aapt resource value: 0x7f050023
			public static int done_text_color_dark_disabled = 2131034147;
			
			// aapt resource value: 0x7f050022
			public static int done_text_color_dark_normal = 2131034146;
			
			// aapt resource value: 0x7f050012
			public static int done_text_color_disabled = 2131034130;
			
			// aapt resource value: 0x7f050011
			public static int done_text_color_normal = 2131034129;
			
			// aapt resource value: 0x7f05001f
			public static int light_gray = 2131034143;
			
			// aapt resource value: 0x7f05000f
			public static int line_background = 2131034127;
			
			// aapt resource value: 0x7f050021
			public static int line_dark = 2131034145;
			
			// aapt resource value: 0x7f050017
			public static int neutral_pressed = 2131034135;
			
			// aapt resource value: 0x7f050013
			public static int numbers_text_color = 2131034131;
			
			// aapt resource value: 0x7f05002d
			public static int recurrence_bubble_text_color = 2131034157;
			
			// aapt resource value: 0x7f050026
			public static int recurrence_bubble_text_normal = 2131034150;
			
			// aapt resource value: 0x7f050025
			public static int recurrence_picker_background = 2131034149;
			
			// aapt resource value: 0x7f05002e
			public static int recurrence_spinner_text_color = 2131034158;
			
			// aapt resource value: 0x7f05001d
			public static int red = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public static int red_focused = 2131034142;
			
			// aapt resource value: 0x7f050000
			public static int transparent = 2131034112;
			
			// aapt resource value: 0x7f050014
			public static int transparent_black = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public static int white = 2131034125;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060011
			public static int ampm_label_size = 2131099665;
			
			// aapt resource value: 0x7f060013
			public static int ampm_left_padding = 2131099667;
			
			// aapt resource value: 0x7f060007
			public static int body_font_padding = 2131099655;
			
			// aapt resource value: 0x7f06001a
			public static int date_picker_component_width = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public static int date_picker_header_height = 2131099675;
			
			// aapt resource value: 0x7f060026
			public static int date_picker_header_text_size = 2131099686;
			
			// aapt resource value: 0x7f06001d
			public static int date_picker_view_animator_height = 2131099677;
			
			// aapt resource value: 0x7f06000e
			public static int date_viewpager_height = 2131099662;
			
			// aapt resource value: 0x7f060021
			public static int day_number_select_circle_radius = 2131099681;
			
			// aapt resource value: 0x7f060028
			public static int day_number_size = 2131099688;
			
			// aapt resource value: 0x7f06000b
			public static int dialog_button_font_size = 2131099659;
			
			// aapt resource value: 0x7f06002d
			public static int dialog_height = 2131099693;
			
			// aapt resource value: 0x7f060008
			public static int dialpad_font_size = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public static int dialpad_font_size_ampm = 2131099658;
			
			// aapt resource value: 0x7f06001e
			public static int done_button_height = 2131099678;
			
			// aapt resource value: 0x7f060012
			public static int done_label_size = 2131099666;
			
			// aapt resource value: 0x7f060010
			public static int extra_time_label_margin = 2131099664;
			
			// aapt resource value: 0x7f060016
			public static int footer_height = 2131099670;
			
			// aapt resource value: 0x7f060015
			public static int header_height = 2131099669;
			
			// aapt resource value: 0x7f060006
			public static int label_font_size = 2131099654;
			
			// aapt resource value: 0x7f06002e
			public static int left_side_width = 2131099694;
			
			// aapt resource value: 0x7f060004
			public static int medium_date_font_size = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int medium_expiration_font_size = 2131099653;
			
			// aapt resource value: 0x7f060000
			public static int medium_font_padding = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int medium_font_size = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int medium_font_size_header = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int medium_font_size_hms = 2131099650;
			
			// aapt resource value: 0x7f060017
			public static int minimum_margin_sides = 2131099671;
			
			// aapt resource value: 0x7f060018
			public static int minimum_margin_top_bottom = 2131099672;
			
			// aapt resource value: 0x7f060020
			public static int month_day_label_text_size = 2131099680;
			
			// aapt resource value: 0x7f060027
			public static int month_label_size = 2131099687;
			
			// aapt resource value: 0x7f06001f
			public static int month_list_item_header_height = 2131099679;
			
			// aapt resource value: 0x7f06002f
			public static int month_list_item_padding = 2131099695;
			
			// aapt resource value: 0x7f060030
			public static int month_list_item_size = 2131099696;
			
			// aapt resource value: 0x7f060022
			public static int month_select_circle_radius = 2131099682;
			
			// aapt resource value: 0x7f060019
			public static int picker_dimen = 2131099673;
			
			// aapt resource value: 0x7f06002b
			public static int recurrence_picker_height = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public static int recurrence_picker_width = 2131099692;
			
			// aapt resource value: 0x7f06001c
			public static int selected_calendar_layout_height = 2131099676;
			
			// aapt resource value: 0x7f060024
			public static int selected_date_day_size = 2131099684;
			
			// aapt resource value: 0x7f060025
			public static int selected_date_month_size = 2131099685;
			
			// aapt resource value: 0x7f060023
			public static int selected_date_year_size = 2131099683;
			
			// aapt resource value: 0x7f060014
			public static int separator_padding = 2131099668;
			
			// aapt resource value: 0x7f06000c
			public static int tablet_dialpad_font_size = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public static int tablet_dialpad_font_size_ampm = 2131099661;
			
			// aapt resource value: 0x7f060031
			public static int time_label_right_padding = 2131099697;
			
			// aapt resource value: 0x7f06000f
			public static int time_label_size = 2131099663;
			
			// aapt resource value: 0x7f060009
			public static int timer_padding_left = 2131099657;
			
			// aapt resource value: 0x7f060029
			public static int year_label_height = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public static int year_label_text_size = 2131099690;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int button_background_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int button_background_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int dialog_full_holo_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int dialog_full_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int done_background_color = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int done_background_color_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int edit_text_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int ic_backspace_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int ic_backspace_disabled_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int ic_backspace_disabled_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int ic_backspace_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int ic_backspace_normal_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int ic_backspace_normal_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int ic_check_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int ic_check_dark_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int ic_check_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int ic_check_light_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int ic_check_normal_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int ic_check_normal_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int ic_clear_search_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int ic_errorstatus = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int ic_recurrence_bubble_disabled = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int ic_recurrence_bubble_fill = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int ic_recurrence_bubble_outline = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int ic_recurrence_bubble_outline_disabled = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int ic_search_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public static int ic_successstatus = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public static int item_background_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public static int key_background_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public static int key_background_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public static int list_focused_holo = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public static int list_longpressed_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public static int list_pressed_holo_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public static int list_selector_background_transition_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public static int list_selector_disabled_holo_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public static int recurrence_bubble_fill = 2130837539;
			
			// aapt resource value: 0x7f020024
			public static int roundedbg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public static int roundedbgdark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public static int spinner_background_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public static int spinner_default_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public static int spinner_disabled_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public static int spinner_focused_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public static int spinner_pressed_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public static int switch_bg_disabled_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public static int switch_bg_focused_holo_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public static int switch_bg_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public static int switch_thumb = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public static int switch_thumb_activated_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public static int switch_thumb_disabled_holo_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public static int switch_thumb_holo_light_v2 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public static int switch_thumb_pressed_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public static int switch_track_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public static int textfield_activated_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public static int textfield_default_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public static int textfield_disabled_focused_holo_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public static int textfield_disabled_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public static int textfield_focused_holo_light = 2130837560;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080040
			public static int ampm_hitspace = 2131230784;
			
			// aapt resource value: 0x7f080041
			public static int ampm_label = 2131230785;
			
			// aapt resource value: 0x7f08000a
			public static int animator = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public static int cancel_button = 2131230734;
			
			// aapt resource value: 0x7f08003a
			public static int center_view = 2131230778;
			
			// aapt resource value: 0x7f080064
			public static int clear_search = 2131230820;
			
			// aapt resource value: 0x7f080013
			public static int date = 2131230739;
			
			// aapt resource value: 0x7f080001
			public static int date_keyboard = 2131230721;
			
			// aapt resource value: 0x7f080002
			public static int date_month_int = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public static int date_picker = 2131230732;
			
			// aapt resource value: 0x7f080008
			public static int date_picker_day = 2131230728;
			
			// aapt resource value: 0x7f080004
			public static int date_picker_header = 2131230724;
			
			// aapt resource value: 0x7f080007
			public static int date_picker_month = 2131230727;
			
			// aapt resource value: 0x7f080006
			public static int date_picker_month_and_day = 2131230726;
			
			// aapt resource value: 0x7f080009
			public static int date_picker_year = 2131230729;
			
			// aapt resource value: 0x7f080011
			public static int date_text = 2131230737;
			
			// aapt resource value: 0x7f080005
			public static int day_picker_selected_date_layout = 2131230725;
			
			// aapt resource value: 0x7f080035
			public static int @decimal = 2131230773;
			
			// aapt resource value: 0x7f080034
			public static int decimal_separator = 2131230772;
			
			// aapt resource value: 0x7f080015
			public static int delete = 2131230741;
			
			// aapt resource value: 0x7f080016
			public static int divider = 2131230742;
			
			// aapt resource value: 0x7f08000d
			public static int divider_1 = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public static int divider_2 = 2131230735;
			
			// aapt resource value: 0x7f080003
			public static int done = 2131230723;
			
			// aapt resource value: 0x7f080046
			public static int done_button = 2131230790;
			
			// aapt resource value: 0x7f080019
			public static int empty_item = 2131230745;
			
			// aapt resource value: 0x7f080055
			public static int endCount = 2131230805;
			
			// aapt resource value: 0x7f080057
			public static int endDate = 2131230807;
			
			// aapt resource value: 0x7f080053
			public static int endGroup = 2131230803;
			
			// aapt resource value: 0x7f080054
			public static int endSpinner = 2131230804;
			
			// aapt resource value: 0x7f080038
			public static int error = 2131230776;
			
			// aapt resource value: 0x7f08001a
			public static int expiration_picker = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public static int expiration_seperator = 2131230747;
			
			// aapt resource value: 0x7f080026
			public static int first = 2131230758;
			
			// aapt resource value: 0x7f080029
			public static int fourth = 2131230761;
			
			// aapt resource value: 0x7f080047
			public static int freqSpinner = 2131230791;
			
			// aapt resource value: 0x7f08002a
			public static int header = 2131230762;
			
			// aapt resource value: 0x7f08001c
			public static int hms_picker = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public static int hms_text = 2131230749;
			
			// aapt resource value: 0x7f080031
			public static int horizontal_scroll_view = 2131230769;
			
			// aapt resource value: 0x7f08003b
			public static int hour_space = 2131230779;
			
			// aapt resource value: 0x7f08003d
			public static int hours = 2131230781;
			
			// aapt resource value: 0x7f08001f
			public static int hours_label = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public static int hours_ones = 2131230750;
			
			// aapt resource value: 0x7f08005e
			public static int hours_seperator = 2131230814;
			
			// aapt resource value: 0x7f08005d
			public static int hours_tens = 2131230813;
			
			// aapt resource value: 0x7f08004c
			public static int interval = 2131230796;
			
			// aapt resource value: 0x7f08004a
			public static int intervalGroup = 2131230794;
			
			// aapt resource value: 0x7f08004d
			public static int intervalPostText = 2131230797;
			
			// aapt resource value: 0x7f08004b
			public static int intervalPreText = 2131230795;
			
			// aapt resource value: 0x7f080059
			public static int key_left = 2131230809;
			
			// aapt resource value: 0x7f08005a
			public static int key_middle = 2131230810;
			
			// aapt resource value: 0x7f08005b
			public static int key_right = 2131230811;
			
			// aapt resource value: 0x7f080017
			public static int keyboard_indicator = 2131230743;
			
			// aapt resource value: 0x7f080018
			public static int keyboard_pager = 2131230744;
			
			// aapt resource value: 0x7f080036
			public static int label = 2131230774;
			
			// aapt resource value: 0x7f080045
			public static int line = 2131230789;
			
			// aapt resource value: 0x7f08002d
			public static int loadingImage = 2131230765;
			
			// aapt resource value: 0x7f08002b
			public static int loadingProgressBar = 2131230763;
			
			// aapt resource value: 0x7f08002e
			public static int loadingProgressWheel = 2131230766;
			
			// aapt resource value: 0x7f080062
			public static int location = 2131230818;
			
			// aapt resource value: 0x7f080037
			public static int minus_label = 2131230775;
			
			// aapt resource value: 0x7f08003f
			public static int minutes = 2131230783;
			
			// aapt resource value: 0x7f080022
			public static int minutes_label = 2131230754;
			
			// aapt resource value: 0x7f080021
			public static int minutes_ones = 2131230753;
			
			// aapt resource value: 0x7f08003e
			public static int minutes_space = 2131230782;
			
			// aapt resource value: 0x7f080020
			public static int minutes_tens = 2131230752;
			
			// aapt resource value: 0x7f080012
			public static int month = 2131230738;
			
			// aapt resource value: 0x7f080050
			public static int monthGroup = 2131230800;
			
			// aapt resource value: 0x7f08000b
			public static int month_text_view = 2131230731;
			
			// aapt resource value: 0x7f080033
			public static int number = 2131230771;
			
			// aapt resource value: 0x7f08002f
			public static int number_picker = 2131230767;
			
			// aapt resource value: 0x7f080032
			public static int number_text = 2131230770;
			
			// aapt resource value: 0x7f080030
			public static int number_view_container = 2131230768;
			
			// aapt resource value: 0x7f080000
			public static int numbers_key = 2131230720;
			
			// aapt resource value: 0x7f080049
			public static int options = 2131230793;
			
			// aapt resource value: 0x7f080056
			public static int postEndCount = 2131230806;
			
			// aapt resource value: 0x7f080051
			public static int repeatMonthlyByNthDayOfMonth = 2131230801;
			
			// aapt resource value: 0x7f080052
			public static int repeatMonthlyByNthDayOfTheWeek = 2131230802;
			
			// aapt resource value: 0x7f080048
			public static int repeat_switch = 2131230792;
			
			// aapt resource value: 0x7f080063
			public static int searchBox = 2131230819;
			
			// aapt resource value: 0x7f080027
			public static int second = 2131230759;
			
			// aapt resource value: 0x7f080025
			public static int seconds_label = 2131230757;
			
			// aapt resource value: 0x7f080024
			public static int seconds_ones = 2131230756;
			
			// aapt resource value: 0x7f080023
			public static int seconds_tens = 2131230755;
			
			// aapt resource value: 0x7f08003c
			public static int separator = 2131230780;
			
			// aapt resource value: 0x7f080010
			public static int set_button = 2131230736;
			
			// aapt resource value: 0x7f080058
			public static int spinner_item = 2131230808;
			
			// aapt resource value: 0x7f08002c
			public static int textViewStatus = 2131230764;
			
			// aapt resource value: 0x7f080028
			public static int third = 2131230760;
			
			// aapt resource value: 0x7f080039
			public static int time_display = 2131230777;
			
			// aapt resource value: 0x7f080043
			public static int time_display_background = 2131230787;
			
			// aapt resource value: 0x7f080061
			public static int time_offset = 2131230817;
			
			// aapt resource value: 0x7f080044
			public static int time_picker = 2131230788;
			
			// aapt resource value: 0x7f080042
			public static int time_picker_dialog = 2131230786;
			
			// aapt resource value: 0x7f080060
			public static int time_zone = 2131230816;
			
			// aapt resource value: 0x7f08005c
			public static int timer_time_text = 2131230812;
			
			// aapt resource value: 0x7f080065
			public static int timezonelist = 2131230821;
			
			// aapt resource value: 0x7f08005f
			public static int value = 2131230815;
			
			// aapt resource value: 0x7f08004e
			public static int weekGroup = 2131230798;
			
			// aapt resource value: 0x7f08004f
			public static int weekGroup2 = 2131230799;
			
			// aapt resource value: 0x7f080014
			public static int year_label = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int calendar_date_picker_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int calendar_date_picker_done_button = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int calendar_date_picker_header_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int calendar_date_picker_selected_date = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int calendar_date_picker_view_animator = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int calendar_year_label_text_view = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int date_picker_dialog = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int date_picker_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int empty_time_zone_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int expiration_picker_dialog = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int expiration_picker_view = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int hms_picker_dialog = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int hms_picker_view = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int keyboard = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int keyboard_right_drawable = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public static int keyboard_right_drawable_with_header = 2130903055;
			
			// aapt resource value: 0x7f030010
			public static int keyboard_text = 2130903056;
			
			// aapt resource value: 0x7f030011
			public static int keyboard_text_with_header = 2130903057;
			
			// aapt resource value: 0x7f030012
			public static int keyboard_with_header = 2130903058;
			
			// aapt resource value: 0x7f030013
			public static int loading = 2130903059;
			
			// aapt resource value: 0x7f030014
			public static int loadingimage = 2130903060;
			
			// aapt resource value: 0x7f030015
			public static int loadingprogress = 2130903061;
			
			// aapt resource value: 0x7f030016
			public static int number_picker_dialog = 2130903062;
			
			// aapt resource value: 0x7f030017
			public static int number_picker_view = 2130903063;
			
			// aapt resource value: 0x7f030018
			public static int radial_time_header_label = 2130903064;
			
			// aapt resource value: 0x7f030019
			public static int radial_time_picker_dialog = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public static int recurrencepicker = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public static int recurrencepicker_end_text = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public static int recurrencepicker_freq_item = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public static int three_keys_view = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public static int three_keys_view_leftright = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public static int three_keys_view_right_drawable = 2130903071;
			
			// aapt resource value: 0x7f030020
			public static int three_keys_view_text = 2130903072;
			
			// aapt resource value: 0x7f030021
			public static int time_picker_dialog = 2130903073;
			
			// aapt resource value: 0x7f030022
			public static int time_picker_view = 2130903074;
			
			// aapt resource value: 0x7f030023
			public static int time_zone_filter_item = 2130903075;
			
			// aapt resource value: 0x7f030024
			public static int time_zone_item = 2130903076;
			
			// aapt resource value: 0x7f030025
			public static int timezonepickerview = 2130903077;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f090006
			public static int daily = 2131296262;
			
			// aapt resource value: 0x7f090005
			public static int endByCount = 2131296261;
			
			// aapt resource value: 0x7f090004
			public static int recurrence_end_count = 2131296260;
			
			// aapt resource value: 0x7f090000
			public static int recurrence_interval_daily = 2131296256;
			
			// aapt resource value: 0x7f090002
			public static int recurrence_interval_monthly = 2131296258;
			
			// aapt resource value: 0x7f090001
			public static int recurrence_interval_weekly = 2131296257;
			
			// aapt resource value: 0x7f090003
			public static int recurrence_interval_yearly = 2131296259;
			
			// aapt resource value: 0x7f090007
			public static int weekly = 2131296263;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070048
			public static int ApplicationName = 2131165256;
			
			// aapt resource value: 0x7f070047
			public static int Hello = 2131165255;
			
			// aapt resource value: 0x7f070036
			public static int acessibility_recurrence_choose_end_date_description = 2131165238;
			
			// aapt resource value: 0x7f070003
			public static int ampm_circle_radius_multiplier = 2131165187;
			
			// aapt resource value: 0x7f070000
			public static int circle_radius_multiplier = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int circle_radius_multiplier_24HourMode = 2131165185;
			
			// aapt resource value: 0x7f070020
			public static int day_c = 2131165216;
			
			// aapt resource value: 0x7f070034
			public static int day_of_week_label_typeface = 2131165236;
			
			// aapt resource value: 0x7f07002a
			public static int day_picker_description = 2131165226;
			
			// aapt resource value: 0x7f07002f
			public static int deleted_key = 2131165231;
			
			// aapt resource value: 0x7f070025
			public static int done_label = 2131165221;
			
			// aapt resource value: 0x7f07003c
			public static int endByDate = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public static int every_weekday = 2131165245;
			
			// aapt resource value: 0x7f07001e
			public static int expiration_picker_seperator = 2131165214;
			
			// aapt resource value: 0x7f070042
			public static int hint_time_zone_search = 2131165250;
			
			// aapt resource value: 0x7f07001b
			public static int hms_picker_hours_label = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public static int hms_picker_minutes_label = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public static int hms_picker_seconds_label = 2131165213;
			
			// aapt resource value: 0x7f070026
			public static int hour_picker_description = 2131165222;
			
			// aapt resource value: 0x7f07000c
			public static int hours_label = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public static int hours_label_description = 2131165199;
			
			// aapt resource value: 0x7f07002e
			public static int item_is_selected = 2131165230;
			
			// aapt resource value: 0x7f070046
			public static int library_name = 2131165254;
			
			// aapt resource value: 0x7f070023
			public static int max_error = 2131165219;
			
			// aapt resource value: 0x7f070022
			public static int min_error = 2131165218;
			
			// aapt resource value: 0x7f070024
			public static int min_max_error = 2131165220;
			
			// aapt resource value: 0x7f070027
			public static int minute_picker_description = 2131165223;
			
			// aapt resource value: 0x7f07000d
			public static int minutes_label = 2131165197;
			
			// aapt resource value: 0x7f070010
			public static int minutes_label_description = 2131165200;
			
			// aapt resource value: 0x7f07001f
			public static int month_c = 2131165215;
			
			// aapt resource value: 0x7f07003e
			public static int monthly = 2131165246;
			
			// aapt resource value: 0x7f070044
			public static int no_results_found = 2131165252;
			
			// aapt resource value: 0x7f070019
			public static int number_delete = 2131165209;
			
			// aapt resource value: 0x7f070017
			public static int number_picker_minus_label = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public static int number_picker_plus_minus = 2131165210;
			
			// aapt resource value: 0x7f070018
			public static int number_picker_seperator = 2131165208;
			
			// aapt resource value: 0x7f070005
			public static int numbers_radius_multiplier_inner = 2131165189;
			
			// aapt resource value: 0x7f070004
			public static int numbers_radius_multiplier_normal = 2131165188;
			
			// aapt resource value: 0x7f070006
			public static int numbers_radius_multiplier_outer = 2131165190;
			
			// aapt resource value: 0x7f070045
			public static int palestine_display_name = 2131165253;
			
			// aapt resource value: 0x7f07000a
			public static int picker_cancel = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public static int picker_set = 2131165195;
			
			// aapt resource value: 0x7f070032
			public static int radial_numbers_typeface = 2131165234;
			
			// aapt resource value: 0x7f070038
			public static int recurrence_end_continously = 2131165240;
			
			// aapt resource value: 0x7f07003b
			public static int recurrence_end_count_label = 2131165243;
			
			// aapt resource value: 0x7f07003a
			public static int recurrence_end_date = 2131165242;
			
			// aapt resource value: 0x7f070039
			public static int recurrence_end_date_label = 2131165241;
			
			// aapt resource value: 0x7f070035
			public static int recurrence_month_pattern_by_day = 2131165237;
			
			// aapt resource value: 0x7f070033
			public static int sans_serif = 2131165235;
			
			// aapt resource value: 0x7f070037
			public static int save_label = 2131165239;
			
			// aapt resource value: 0x7f070043
			public static int searchview_description_clear = 2131165251;
			
			// aapt resource value: 0x7f07000e
			public static int seconds_label = 2131165198;
			
			// aapt resource value: 0x7f070011
			public static int seconds_label_description = 2131165201;
			
			// aapt resource value: 0x7f07002c
			public static int select_day = 2131165228;
			
			// aapt resource value: 0x7f070028
			public static int select_hours = 2131165224;
			
			// aapt resource value: 0x7f070029
			public static int select_minutes = 2131165225;
			
			// aapt resource value: 0x7f07002d
			public static int select_year = 2131165229;
			
			// aapt resource value: 0x7f070002
			public static int selection_radius_multiplier = 2131165186;
			
			// aapt resource value: 0x7f070041
			public static int switch_off = 2131165249;
			
			// aapt resource value: 0x7f070040
			public static int switch_on = 2131165248;
			
			// aapt resource value: 0x7f070008
			public static int text_size_multiplier_inner = 2131165192;
			
			// aapt resource value: 0x7f070007
			public static int text_size_multiplier_normal = 2131165191;
			
			// aapt resource value: 0x7f070009
			public static int text_size_multiplier_outer = 2131165193;
			
			// aapt resource value: 0x7f070015
			public static int time_picker_00_label = 2131165205;
			
			// aapt resource value: 0x7f070016
			public static int time_picker_30_label = 2131165206;
			
			// aapt resource value: 0x7f070013
			public static int time_picker_ampm_label = 2131165203;
			
			// aapt resource value: 0x7f070014
			public static int time_picker_time_seperator = 2131165204;
			
			// aapt resource value: 0x7f070030
			public static int time_placeholder = 2131165232;
			
			// aapt resource value: 0x7f070031
			public static int time_separator = 2131165233;
			
			// aapt resource value: 0x7f070012
			public static int timer_delete = 2131165202;
			
			// aapt resource value: 0x7f070021
			public static int year_c = 2131165217;
			
			// aapt resource value: 0x7f07002b
			public static int year_picker_description = 2131165227;
			
			// aapt resource value: 0x7f07003f
			public static int yearly_plain = 2131165247;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0017
			public static int BetterPickersDialogFragment = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public static int BetterPickersDialogFragment_Light = 2131361816;
			
			// aapt resource value: 0x7f0a0014
			public static int RecurrenceDayOfWeekStyle = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public static int TextAppearance_EditEvent_Spinner = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public static int TextAppearance_EditEvent_SpinnerButton = 2131361814;
			
			// aapt resource value: 0x7f0a0012
			public static int TextAppearance_Holo_Light_Widget_Switch = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public static int TextAppearance_RecurrencePickerStyle = 2131361811;
			
			// aapt resource value: 0x7f0a0011
			public static int Widget_Holo_Light_CompoundButton_Switch = 2131361809;
			
			// aapt resource value: 0x7f0a000f
			public static int aosp_ampm_label = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public static int aosp_day_of_week_label_condensed = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public static int aosp_time_label = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public static int dialog_button = 2131361803;
			
			// aapt resource value: 0x7f0a0009
			public static int dialpad = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public static int dialpad_text = 2131361802;
			
			// aapt resource value: 0x7f0a0008
			public static int label = 2131361800;
			
			// aapt resource value: 0x7f0a0000
			public static int medium_bold = 2131361792;
			
			// aapt resource value: 0x7f0a0005
			public static int medium_bold_date = 2131361797;
			
			// aapt resource value: 0x7f0a0001
			public static int medium_bold_hms = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public static int medium_light = 2131361794;
			
			// aapt resource value: 0x7f0a0006
			public static int medium_light_date = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public static int medium_light_expiration = 2131361799;
			
			// aapt resource value: 0x7f0a0003
			public static int medium_light_header = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public static int medium_light_hms = 2131361796;
			
			// aapt resource value: 0x7f0a000c
			public static int tablet_dialpad = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public static int tablet_dialpad_text = 2131361805;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Android = new int[] {
					16842901,
					16842902,
					16842903,
					16842904,
					16842905,
					16842906,
					16842907};
			
			// aapt resource value: 3
			public static int Android_android_textColor = 3;
			
			// aapt resource value: 4
			public static int Android_android_textColorHighlight = 4;
			
			// aapt resource value: 5
			public static int Android_android_textColorHint = 5;
			
			// aapt resource value: 6
			public static int Android_android_textColorLink = 6;
			
			// aapt resource value: 0
			public static int Android_android_textSize = 0;
			
			// aapt resource value: 2
			public static int Android_android_textStyle = 2;
			
			// aapt resource value: 1
			public static int Android_android_typeface = 1;
			
			public static int[] BetterPickersDialogFragment = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 5
			public static int BetterPickersDialogFragment_bpButtonBackground = 5;
			
			// aapt resource value: 3
			public static int BetterPickersDialogFragment_bpCheckIcon = 3;
			
			// aapt resource value: 2
			public static int BetterPickersDialogFragment_bpDeleteIcon = 2;
			
			// aapt resource value: 9
			public static int BetterPickersDialogFragment_bpDialogBackground = 9;
			
			// aapt resource value: 7
			public static int BetterPickersDialogFragment_bpDividerColor = 7;
			
			// aapt resource value: 4
			public static int BetterPickersDialogFragment_bpKeyBackground = 4;
			
			// aapt resource value: 8
			public static int BetterPickersDialogFragment_bpKeyboardIndicatorColor = 8;
			
			// aapt resource value: 0
			public static int BetterPickersDialogFragment_bpTextColor = 0;
			
			// aapt resource value: 1
			public static int BetterPickersDialogFragment_bpTitleColor = 1;
			
			// aapt resource value: 6
			public static int BetterPickersDialogFragment_bpTitleDividerColor = 6;
			
			public static int[] BetterPickersSwitchTheme = new int[] {
					2130771986,
					2130771987};
			
			// aapt resource value: 1
			public static int BetterPickersSwitchTheme_switchPreferenceStyle = 1;
			
			// aapt resource value: 0
			public static int BetterPickersSwitchTheme_switchStyle = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999};
			
			// aapt resource value: 3
			public static int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public static int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public static int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public static int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public static int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public static int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public static int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public static int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public static int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public static int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public static int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public static int ProgressWheel_ahTextSize = 2;
			
			public static int[] Switch = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 6
			public static int Switch_switchMinWidth = 6;
			
			// aapt resource value: 7
			public static int Switch_switchPadding = 7;
			
			// aapt resource value: 5
			public static int Switch_switchTextAppearance = 5;
			
			// aapt resource value: 3
			public static int Switch_textOff = 3;
			
			// aapt resource value: 2
			public static int Switch_textOn = 2;
			
			// aapt resource value: 0
			public static int Switch_thumb = 0;
			
			// aapt resource value: 4
			public static int Switch_thumbTextPadding = 4;
			
			// aapt resource value: 1
			public static int Switch_track = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
