#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Samples.Droid.Resource", IsApplication=true)]

namespace Samples.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.UserDialogs.Resource.Array.backup_country_codes = global::Samples.Droid.Resource.Array.backup_country_codes;
			global::Acr.UserDialogs.Resource.Array.backup_country_names = global::Samples.Droid.Resource.Array.backup_country_names;
			global::Acr.UserDialogs.Resource.Array.recurrence_freq = global::Samples.Droid.Resource.Array.recurrence_freq;
			global::Acr.UserDialogs.Resource.Array.repeat_by_nth_fri = global::Samples.Droid.Resource.Array.repeat_by_nth_fri;
			global::Acr.UserDialogs.Resource.Array.repeat_by_nth_mon = global::Samples.Droid.Resource.Array.repeat_by_nth_mon;
			global::Acr.UserDialogs.Resource.Array.repeat_by_nth_sat = global::Samples.Droid.Resource.Array.repeat_by_nth_sat;
			global::Acr.UserDialogs.Resource.Array.repeat_by_nth_sun = global::Samples.Droid.Resource.Array.repeat_by_nth_sun;
			global::Acr.UserDialogs.Resource.Array.repeat_by_nth_thurs = global::Samples.Droid.Resource.Array.repeat_by_nth_thurs;
			global::Acr.UserDialogs.Resource.Array.repeat_by_nth_tues = global::Samples.Droid.Resource.Array.repeat_by_nth_tues;
			global::Acr.UserDialogs.Resource.Array.repeat_by_nth_wed = global::Samples.Droid.Resource.Array.repeat_by_nth_wed;
			global::Acr.UserDialogs.Resource.Array.timezone_rename_ids = global::Samples.Droid.Resource.Array.timezone_rename_ids;
			global::Acr.UserDialogs.Resource.Array.timezone_rename_labels = global::Samples.Droid.Resource.Array.timezone_rename_labels;
			global::Acr.UserDialogs.Resource.Attribute.ahBarColor = global::Samples.Droid.Resource.Attribute.ahBarColor;
			global::Acr.UserDialogs.Resource.Attribute.ahBarLength = global::Samples.Droid.Resource.Attribute.ahBarLength;
			global::Acr.UserDialogs.Resource.Attribute.ahBarWidth = global::Samples.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahCircleColor = global::Samples.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.UserDialogs.Resource.Attribute.ahDelayMillis = global::Samples.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.UserDialogs.Resource.Attribute.ahRadius = global::Samples.Droid.Resource.Attribute.ahRadius;
			global::Acr.UserDialogs.Resource.Attribute.ahRimColor = global::Samples.Droid.Resource.Attribute.ahRimColor;
			global::Acr.UserDialogs.Resource.Attribute.ahRimWidth = global::Samples.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.UserDialogs.Resource.Attribute.ahSpinSpeed = global::Samples.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Attribute.ahText = global::Samples.Droid.Resource.Attribute.ahText;
			global::Acr.UserDialogs.Resource.Attribute.ahTextColor = global::Samples.Droid.Resource.Attribute.ahTextColor;
			global::Acr.UserDialogs.Resource.Attribute.ahTextSize = global::Samples.Droid.Resource.Attribute.ahTextSize;
			global::Acr.UserDialogs.Resource.Attribute.bpButtonBackground = global::Samples.Droid.Resource.Attribute.bpButtonBackground;
			global::Acr.UserDialogs.Resource.Attribute.bpCheckIcon = global::Samples.Droid.Resource.Attribute.bpCheckIcon;
			global::Acr.UserDialogs.Resource.Attribute.bpDeleteIcon = global::Samples.Droid.Resource.Attribute.bpDeleteIcon;
			global::Acr.UserDialogs.Resource.Attribute.bpDialogBackground = global::Samples.Droid.Resource.Attribute.bpDialogBackground;
			global::Acr.UserDialogs.Resource.Attribute.bpDividerColor = global::Samples.Droid.Resource.Attribute.bpDividerColor;
			global::Acr.UserDialogs.Resource.Attribute.bpKeyBackground = global::Samples.Droid.Resource.Attribute.bpKeyBackground;
			global::Acr.UserDialogs.Resource.Attribute.bpKeyboardIndicatorColor = global::Samples.Droid.Resource.Attribute.bpKeyboardIndicatorColor;
			global::Acr.UserDialogs.Resource.Attribute.bpTextColor = global::Samples.Droid.Resource.Attribute.bpTextColor;
			global::Acr.UserDialogs.Resource.Attribute.bpTitleColor = global::Samples.Droid.Resource.Attribute.bpTitleColor;
			global::Acr.UserDialogs.Resource.Attribute.bpTitleDividerColor = global::Samples.Droid.Resource.Attribute.bpTitleDividerColor;
			global::Acr.UserDialogs.Resource.Attribute.switchMinWidth = global::Samples.Droid.Resource.Attribute.switchMinWidth;
			global::Acr.UserDialogs.Resource.Attribute.switchPadding = global::Samples.Droid.Resource.Attribute.switchPadding;
			global::Acr.UserDialogs.Resource.Attribute.switchPreferenceStyle = global::Samples.Droid.Resource.Attribute.switchPreferenceStyle;
			global::Acr.UserDialogs.Resource.Attribute.switchStyle = global::Samples.Droid.Resource.Attribute.switchStyle;
			global::Acr.UserDialogs.Resource.Attribute.switchTextAppearance = global::Samples.Droid.Resource.Attribute.switchTextAppearance;
			global::Acr.UserDialogs.Resource.Attribute.textOff = global::Samples.Droid.Resource.Attribute.textOff;
			global::Acr.UserDialogs.Resource.Attribute.textOn = global::Samples.Droid.Resource.Attribute.textOn;
			global::Acr.UserDialogs.Resource.Attribute.thumb = global::Samples.Droid.Resource.Attribute.thumb;
			global::Acr.UserDialogs.Resource.Attribute.thumbTextPadding = global::Samples.Droid.Resource.Attribute.thumbTextPadding;
			global::Acr.UserDialogs.Resource.Attribute.track = global::Samples.Droid.Resource.Attribute.track;
			global::Acr.UserDialogs.Resource.Color.ampm_text_color = global::Samples.Droid.Resource.Color.ampm_text_color;
			global::Acr.UserDialogs.Resource.Color.blue = global::Samples.Droid.Resource.Color.blue;
			global::Acr.UserDialogs.Resource.Color.blue_focused = global::Samples.Droid.Resource.Color.blue_focused;
			global::Acr.UserDialogs.Resource.Color.calendar_header = global::Samples.Droid.Resource.Color.calendar_header;
			global::Acr.UserDialogs.Resource.Color.calendar_selected_date_text = global::Samples.Droid.Resource.Color.calendar_selected_date_text;
			global::Acr.UserDialogs.Resource.Color.circle_background = global::Samples.Droid.Resource.Color.circle_background;
			global::Acr.UserDialogs.Resource.Color.dark_gray = global::Samples.Droid.Resource.Color.dark_gray;
			global::Acr.UserDialogs.Resource.Color.darker_blue = global::Samples.Droid.Resource.Color.darker_blue;
			global::Acr.UserDialogs.Resource.Color.date_picker_selector = global::Samples.Droid.Resource.Color.date_picker_selector;
			global::Acr.UserDialogs.Resource.Color.date_picker_text_normal = global::Samples.Droid.Resource.Color.date_picker_text_normal;
			global::Acr.UserDialogs.Resource.Color.date_picker_view_animator = global::Samples.Droid.Resource.Color.date_picker_view_animator;
			global::Acr.UserDialogs.Resource.Color.date_picker_year_selector = global::Samples.Droid.Resource.Color.date_picker_year_selector;
			global::Acr.UserDialogs.Resource.Color.default_button_background_dark = global::Samples.Droid.Resource.Color.default_button_background_dark;
			global::Acr.UserDialogs.Resource.Color.default_button_background_light = global::Samples.Droid.Resource.Color.default_button_background_light;
			global::Acr.UserDialogs.Resource.Color.default_button_background_pressed_dark = global::Samples.Droid.Resource.Color.default_button_background_pressed_dark;
			global::Acr.UserDialogs.Resource.Color.default_button_background_pressed_light = global::Samples.Droid.Resource.Color.default_button_background_pressed_light;
			global::Acr.UserDialogs.Resource.Color.default_divider_color_dark = global::Samples.Droid.Resource.Color.default_divider_color_dark;
			global::Acr.UserDialogs.Resource.Color.default_divider_color_light = global::Samples.Droid.Resource.Color.default_divider_color_light;
			global::Acr.UserDialogs.Resource.Color.default_keyboard_indicator_color_dark = global::Samples.Droid.Resource.Color.default_keyboard_indicator_color_dark;
			global::Acr.UserDialogs.Resource.Color.default_keyboard_indicator_color_light = global::Samples.Droid.Resource.Color.default_keyboard_indicator_color_light;
			global::Acr.UserDialogs.Resource.Color.default_text_color_holo_dark = global::Samples.Droid.Resource.Color.default_text_color_holo_dark;
			global::Acr.UserDialogs.Resource.Color.default_text_color_holo_dark_disabled = global::Samples.Droid.Resource.Color.default_text_color_holo_dark_disabled;
			global::Acr.UserDialogs.Resource.Color.default_text_color_holo_light = global::Samples.Droid.Resource.Color.default_text_color_holo_light;
			global::Acr.UserDialogs.Resource.Color.default_text_color_holo_light_disabled = global::Samples.Droid.Resource.Color.default_text_color_holo_light_disabled;
			global::Acr.UserDialogs.Resource.Color.dialog_text_color_holo_dark = global::Samples.Droid.Resource.Color.dialog_text_color_holo_dark;
			global::Acr.UserDialogs.Resource.Color.dialog_text_color_holo_light = global::Samples.Droid.Resource.Color.dialog_text_color_holo_light;
			global::Acr.UserDialogs.Resource.Color.done_disabled_dark = global::Samples.Droid.Resource.Color.done_disabled_dark;
			global::Acr.UserDialogs.Resource.Color.done_text_color = global::Samples.Droid.Resource.Color.done_text_color;
			global::Acr.UserDialogs.Resource.Color.done_text_color_dark = global::Samples.Droid.Resource.Color.done_text_color_dark;
			global::Acr.UserDialogs.Resource.Color.done_text_color_dark_disabled = global::Samples.Droid.Resource.Color.done_text_color_dark_disabled;
			global::Acr.UserDialogs.Resource.Color.done_text_color_dark_normal = global::Samples.Droid.Resource.Color.done_text_color_dark_normal;
			global::Acr.UserDialogs.Resource.Color.done_text_color_disabled = global::Samples.Droid.Resource.Color.done_text_color_disabled;
			global::Acr.UserDialogs.Resource.Color.done_text_color_normal = global::Samples.Droid.Resource.Color.done_text_color_normal;
			global::Acr.UserDialogs.Resource.Color.light_gray = global::Samples.Droid.Resource.Color.light_gray;
			global::Acr.UserDialogs.Resource.Color.line_background = global::Samples.Droid.Resource.Color.line_background;
			global::Acr.UserDialogs.Resource.Color.line_dark = global::Samples.Droid.Resource.Color.line_dark;
			global::Acr.UserDialogs.Resource.Color.neutral_pressed = global::Samples.Droid.Resource.Color.neutral_pressed;
			global::Acr.UserDialogs.Resource.Color.numbers_text_color = global::Samples.Droid.Resource.Color.numbers_text_color;
			global::Acr.UserDialogs.Resource.Color.recurrence_bubble_text_color = global::Samples.Droid.Resource.Color.recurrence_bubble_text_color;
			global::Acr.UserDialogs.Resource.Color.recurrence_bubble_text_normal = global::Samples.Droid.Resource.Color.recurrence_bubble_text_normal;
			global::Acr.UserDialogs.Resource.Color.recurrence_picker_background = global::Samples.Droid.Resource.Color.recurrence_picker_background;
			global::Acr.UserDialogs.Resource.Color.recurrence_spinner_text_color = global::Samples.Droid.Resource.Color.recurrence_spinner_text_color;
			global::Acr.UserDialogs.Resource.Color.red = global::Samples.Droid.Resource.Color.red;
			global::Acr.UserDialogs.Resource.Color.red_focused = global::Samples.Droid.Resource.Color.red_focused;
			global::Acr.UserDialogs.Resource.Color.transparent = global::Samples.Droid.Resource.Color.transparent;
			global::Acr.UserDialogs.Resource.Color.transparent_black = global::Samples.Droid.Resource.Color.transparent_black;
			global::Acr.UserDialogs.Resource.Color.white = global::Samples.Droid.Resource.Color.white;
			global::Acr.UserDialogs.Resource.Dimension.ampm_label_size = global::Samples.Droid.Resource.Dimension.ampm_label_size;
			global::Acr.UserDialogs.Resource.Dimension.ampm_left_padding = global::Samples.Droid.Resource.Dimension.ampm_left_padding;
			global::Acr.UserDialogs.Resource.Dimension.body_font_padding = global::Samples.Droid.Resource.Dimension.body_font_padding;
			global::Acr.UserDialogs.Resource.Dimension.date_picker_component_width = global::Samples.Droid.Resource.Dimension.date_picker_component_width;
			global::Acr.UserDialogs.Resource.Dimension.date_picker_header_height = global::Samples.Droid.Resource.Dimension.date_picker_header_height;
			global::Acr.UserDialogs.Resource.Dimension.date_picker_header_text_size = global::Samples.Droid.Resource.Dimension.date_picker_header_text_size;
			global::Acr.UserDialogs.Resource.Dimension.date_picker_view_animator_height = global::Samples.Droid.Resource.Dimension.date_picker_view_animator_height;
			global::Acr.UserDialogs.Resource.Dimension.date_viewpager_height = global::Samples.Droid.Resource.Dimension.date_viewpager_height;
			global::Acr.UserDialogs.Resource.Dimension.day_number_select_circle_radius = global::Samples.Droid.Resource.Dimension.day_number_select_circle_radius;
			global::Acr.UserDialogs.Resource.Dimension.day_number_size = global::Samples.Droid.Resource.Dimension.day_number_size;
			global::Acr.UserDialogs.Resource.Dimension.dialog_button_font_size = global::Samples.Droid.Resource.Dimension.dialog_button_font_size;
			global::Acr.UserDialogs.Resource.Dimension.dialog_height = global::Samples.Droid.Resource.Dimension.dialog_height;
			global::Acr.UserDialogs.Resource.Dimension.dialpad_font_size = global::Samples.Droid.Resource.Dimension.dialpad_font_size;
			global::Acr.UserDialogs.Resource.Dimension.dialpad_font_size_ampm = global::Samples.Droid.Resource.Dimension.dialpad_font_size_ampm;
			global::Acr.UserDialogs.Resource.Dimension.done_button_height = global::Samples.Droid.Resource.Dimension.done_button_height;
			global::Acr.UserDialogs.Resource.Dimension.done_label_size = global::Samples.Droid.Resource.Dimension.done_label_size;
			global::Acr.UserDialogs.Resource.Dimension.extra_time_label_margin = global::Samples.Droid.Resource.Dimension.extra_time_label_margin;
			global::Acr.UserDialogs.Resource.Dimension.footer_height = global::Samples.Droid.Resource.Dimension.footer_height;
			global::Acr.UserDialogs.Resource.Dimension.header_height = global::Samples.Droid.Resource.Dimension.header_height;
			global::Acr.UserDialogs.Resource.Dimension.label_font_size = global::Samples.Droid.Resource.Dimension.label_font_size;
			global::Acr.UserDialogs.Resource.Dimension.left_side_width = global::Samples.Droid.Resource.Dimension.left_side_width;
			global::Acr.UserDialogs.Resource.Dimension.medium_date_font_size = global::Samples.Droid.Resource.Dimension.medium_date_font_size;
			global::Acr.UserDialogs.Resource.Dimension.medium_expiration_font_size = global::Samples.Droid.Resource.Dimension.medium_expiration_font_size;
			global::Acr.UserDialogs.Resource.Dimension.medium_font_padding = global::Samples.Droid.Resource.Dimension.medium_font_padding;
			global::Acr.UserDialogs.Resource.Dimension.medium_font_size = global::Samples.Droid.Resource.Dimension.medium_font_size;
			global::Acr.UserDialogs.Resource.Dimension.medium_font_size_header = global::Samples.Droid.Resource.Dimension.medium_font_size_header;
			global::Acr.UserDialogs.Resource.Dimension.medium_font_size_hms = global::Samples.Droid.Resource.Dimension.medium_font_size_hms;
			global::Acr.UserDialogs.Resource.Dimension.minimum_margin_sides = global::Samples.Droid.Resource.Dimension.minimum_margin_sides;
			global::Acr.UserDialogs.Resource.Dimension.minimum_margin_top_bottom = global::Samples.Droid.Resource.Dimension.minimum_margin_top_bottom;
			global::Acr.UserDialogs.Resource.Dimension.month_day_label_text_size = global::Samples.Droid.Resource.Dimension.month_day_label_text_size;
			global::Acr.UserDialogs.Resource.Dimension.month_label_size = global::Samples.Droid.Resource.Dimension.month_label_size;
			global::Acr.UserDialogs.Resource.Dimension.month_list_item_header_height = global::Samples.Droid.Resource.Dimension.month_list_item_header_height;
			global::Acr.UserDialogs.Resource.Dimension.month_list_item_padding = global::Samples.Droid.Resource.Dimension.month_list_item_padding;
			global::Acr.UserDialogs.Resource.Dimension.month_list_item_size = global::Samples.Droid.Resource.Dimension.month_list_item_size;
			global::Acr.UserDialogs.Resource.Dimension.month_select_circle_radius = global::Samples.Droid.Resource.Dimension.month_select_circle_radius;
			global::Acr.UserDialogs.Resource.Dimension.picker_dimen = global::Samples.Droid.Resource.Dimension.picker_dimen;
			global::Acr.UserDialogs.Resource.Dimension.recurrence_picker_height = global::Samples.Droid.Resource.Dimension.recurrence_picker_height;
			global::Acr.UserDialogs.Resource.Dimension.recurrence_picker_width = global::Samples.Droid.Resource.Dimension.recurrence_picker_width;
			global::Acr.UserDialogs.Resource.Dimension.selected_calendar_layout_height = global::Samples.Droid.Resource.Dimension.selected_calendar_layout_height;
			global::Acr.UserDialogs.Resource.Dimension.selected_date_day_size = global::Samples.Droid.Resource.Dimension.selected_date_day_size;
			global::Acr.UserDialogs.Resource.Dimension.selected_date_month_size = global::Samples.Droid.Resource.Dimension.selected_date_month_size;
			global::Acr.UserDialogs.Resource.Dimension.selected_date_year_size = global::Samples.Droid.Resource.Dimension.selected_date_year_size;
			global::Acr.UserDialogs.Resource.Dimension.separator_padding = global::Samples.Droid.Resource.Dimension.separator_padding;
			global::Acr.UserDialogs.Resource.Dimension.tablet_dialpad_font_size = global::Samples.Droid.Resource.Dimension.tablet_dialpad_font_size;
			global::Acr.UserDialogs.Resource.Dimension.tablet_dialpad_font_size_ampm = global::Samples.Droid.Resource.Dimension.tablet_dialpad_font_size_ampm;
			global::Acr.UserDialogs.Resource.Dimension.time_label_right_padding = global::Samples.Droid.Resource.Dimension.time_label_right_padding;
			global::Acr.UserDialogs.Resource.Dimension.time_label_size = global::Samples.Droid.Resource.Dimension.time_label_size;
			global::Acr.UserDialogs.Resource.Dimension.timer_padding_left = global::Samples.Droid.Resource.Dimension.timer_padding_left;
			global::Acr.UserDialogs.Resource.Dimension.year_label_height = global::Samples.Droid.Resource.Dimension.year_label_height;
			global::Acr.UserDialogs.Resource.Dimension.year_label_text_size = global::Samples.Droid.Resource.Dimension.year_label_text_size;
			global::Acr.UserDialogs.Resource.Drawable.button_background_dark = global::Samples.Droid.Resource.Drawable.button_background_dark;
			global::Acr.UserDialogs.Resource.Drawable.button_background_light = global::Samples.Droid.Resource.Drawable.button_background_light;
			global::Acr.UserDialogs.Resource.Drawable.dialog_full_holo_dark = global::Samples.Droid.Resource.Drawable.dialog_full_holo_dark;
			global::Acr.UserDialogs.Resource.Drawable.dialog_full_holo_light = global::Samples.Droid.Resource.Drawable.dialog_full_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.done_background_color = global::Samples.Droid.Resource.Drawable.done_background_color;
			global::Acr.UserDialogs.Resource.Drawable.done_background_color_dark = global::Samples.Droid.Resource.Drawable.done_background_color_dark;
			global::Acr.UserDialogs.Resource.Drawable.edit_text_holo_light = global::Samples.Droid.Resource.Drawable.edit_text_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_backspace_dark = global::Samples.Droid.Resource.Drawable.ic_backspace_dark;
			global::Acr.UserDialogs.Resource.Drawable.ic_backspace_disabled_dark = global::Samples.Droid.Resource.Drawable.ic_backspace_disabled_dark;
			global::Acr.UserDialogs.Resource.Drawable.ic_backspace_disabled_light = global::Samples.Droid.Resource.Drawable.ic_backspace_disabled_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_backspace_light = global::Samples.Droid.Resource.Drawable.ic_backspace_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_backspace_normal_dark = global::Samples.Droid.Resource.Drawable.ic_backspace_normal_dark;
			global::Acr.UserDialogs.Resource.Drawable.ic_backspace_normal_light = global::Samples.Droid.Resource.Drawable.ic_backspace_normal_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_check_dark = global::Samples.Droid.Resource.Drawable.ic_check_dark;
			global::Acr.UserDialogs.Resource.Drawable.ic_check_dark_disabled = global::Samples.Droid.Resource.Drawable.ic_check_dark_disabled;
			global::Acr.UserDialogs.Resource.Drawable.ic_check_light = global::Samples.Droid.Resource.Drawable.ic_check_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_check_light_disabled = global::Samples.Droid.Resource.Drawable.ic_check_light_disabled;
			global::Acr.UserDialogs.Resource.Drawable.ic_check_normal_dark = global::Samples.Droid.Resource.Drawable.ic_check_normal_dark;
			global::Acr.UserDialogs.Resource.Drawable.ic_check_normal_light = global::Samples.Droid.Resource.Drawable.ic_check_normal_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_clear_search_holo_light = global::Samples.Droid.Resource.Drawable.ic_clear_search_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_errorstatus = global::Samples.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.UserDialogs.Resource.Drawable.ic_recurrence_bubble_disabled = global::Samples.Droid.Resource.Drawable.ic_recurrence_bubble_disabled;
			global::Acr.UserDialogs.Resource.Drawable.ic_recurrence_bubble_fill = global::Samples.Droid.Resource.Drawable.ic_recurrence_bubble_fill;
			global::Acr.UserDialogs.Resource.Drawable.ic_recurrence_bubble_outline = global::Samples.Droid.Resource.Drawable.ic_recurrence_bubble_outline;
			global::Acr.UserDialogs.Resource.Drawable.ic_recurrence_bubble_outline_disabled = global::Samples.Droid.Resource.Drawable.ic_recurrence_bubble_outline_disabled;
			global::Acr.UserDialogs.Resource.Drawable.ic_search_holo_light = global::Samples.Droid.Resource.Drawable.ic_search_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.ic_successstatus = global::Samples.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.UserDialogs.Resource.Drawable.item_background_holo_light = global::Samples.Droid.Resource.Drawable.item_background_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.key_background_dark = global::Samples.Droid.Resource.Drawable.key_background_dark;
			global::Acr.UserDialogs.Resource.Drawable.key_background_light = global::Samples.Droid.Resource.Drawable.key_background_light;
			global::Acr.UserDialogs.Resource.Drawable.list_focused_holo = global::Samples.Droid.Resource.Drawable.list_focused_holo;
			global::Acr.UserDialogs.Resource.Drawable.list_longpressed_holo_light = global::Samples.Droid.Resource.Drawable.list_longpressed_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.list_pressed_holo_light = global::Samples.Droid.Resource.Drawable.list_pressed_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.list_selector_background_transition_holo_light = global::Samples.Droid.Resource.Drawable.list_selector_background_transition_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.list_selector_disabled_holo_light = global::Samples.Droid.Resource.Drawable.list_selector_disabled_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.recurrence_bubble_fill = global::Samples.Droid.Resource.Drawable.recurrence_bubble_fill;
			global::Acr.UserDialogs.Resource.Drawable.roundedbg = global::Samples.Droid.Resource.Drawable.roundedbg;
			global::Acr.UserDialogs.Resource.Drawable.roundedbgdark = global::Samples.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.UserDialogs.Resource.Drawable.spinner_background_holo_light = global::Samples.Droid.Resource.Drawable.spinner_background_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.spinner_default_holo_light = global::Samples.Droid.Resource.Drawable.spinner_default_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.spinner_disabled_holo_light = global::Samples.Droid.Resource.Drawable.spinner_disabled_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.spinner_focused_holo_light = global::Samples.Droid.Resource.Drawable.spinner_focused_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.spinner_pressed_holo_light = global::Samples.Droid.Resource.Drawable.spinner_pressed_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.switch_bg_disabled_holo_light = global::Samples.Droid.Resource.Drawable.switch_bg_disabled_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.switch_bg_focused_holo_light = global::Samples.Droid.Resource.Drawable.switch_bg_focused_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.switch_bg_holo_light = global::Samples.Droid.Resource.Drawable.switch_bg_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.switch_thumb = global::Samples.Droid.Resource.Drawable.switch_thumb;
			global::Acr.UserDialogs.Resource.Drawable.switch_thumb_activated_holo_light = global::Samples.Droid.Resource.Drawable.switch_thumb_activated_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.switch_thumb_disabled_holo_light = global::Samples.Droid.Resource.Drawable.switch_thumb_disabled_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.switch_thumb_holo_light_v2 = global::Samples.Droid.Resource.Drawable.switch_thumb_holo_light_v2;
			global::Acr.UserDialogs.Resource.Drawable.switch_thumb_pressed_holo_light = global::Samples.Droid.Resource.Drawable.switch_thumb_pressed_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.switch_track_holo_light = global::Samples.Droid.Resource.Drawable.switch_track_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.textfield_activated_holo_light = global::Samples.Droid.Resource.Drawable.textfield_activated_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.textfield_default_holo_light = global::Samples.Droid.Resource.Drawable.textfield_default_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.textfield_disabled_focused_holo_light = global::Samples.Droid.Resource.Drawable.textfield_disabled_focused_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.textfield_disabled_holo_light = global::Samples.Droid.Resource.Drawable.textfield_disabled_holo_light;
			global::Acr.UserDialogs.Resource.Drawable.textfield_focused_holo_light = global::Samples.Droid.Resource.Drawable.textfield_focused_holo_light;
			global::Acr.UserDialogs.Resource.Id.ampm_hitspace = global::Samples.Droid.Resource.Id.ampm_hitspace;
			global::Acr.UserDialogs.Resource.Id.ampm_label = global::Samples.Droid.Resource.Id.ampm_label;
			global::Acr.UserDialogs.Resource.Id.animator = global::Samples.Droid.Resource.Id.animator;
			global::Acr.UserDialogs.Resource.Id.cancel_button = global::Samples.Droid.Resource.Id.cancel_button;
			global::Acr.UserDialogs.Resource.Id.center_view = global::Samples.Droid.Resource.Id.center_view;
			global::Acr.UserDialogs.Resource.Id.clear_search = global::Samples.Droid.Resource.Id.clear_search;
			global::Acr.UserDialogs.Resource.Id.date = global::Samples.Droid.Resource.Id.date;
			global::Acr.UserDialogs.Resource.Id.date_keyboard = global::Samples.Droid.Resource.Id.date_keyboard;
			global::Acr.UserDialogs.Resource.Id.date_month_int = global::Samples.Droid.Resource.Id.date_month_int;
			global::Acr.UserDialogs.Resource.Id.date_picker = global::Samples.Droid.Resource.Id.date_picker;
			global::Acr.UserDialogs.Resource.Id.date_picker_day = global::Samples.Droid.Resource.Id.date_picker_day;
			global::Acr.UserDialogs.Resource.Id.date_picker_header = global::Samples.Droid.Resource.Id.date_picker_header;
			global::Acr.UserDialogs.Resource.Id.date_picker_month = global::Samples.Droid.Resource.Id.date_picker_month;
			global::Acr.UserDialogs.Resource.Id.date_picker_month_and_day = global::Samples.Droid.Resource.Id.date_picker_month_and_day;
			global::Acr.UserDialogs.Resource.Id.date_picker_year = global::Samples.Droid.Resource.Id.date_picker_year;
			global::Acr.UserDialogs.Resource.Id.date_text = global::Samples.Droid.Resource.Id.date_text;
			global::Acr.UserDialogs.Resource.Id.day_picker_selected_date_layout = global::Samples.Droid.Resource.Id.day_picker_selected_date_layout;
			global::Acr.UserDialogs.Resource.Id.@decimal = global::Samples.Droid.Resource.Id.@decimal;
			global::Acr.UserDialogs.Resource.Id.decimal_separator = global::Samples.Droid.Resource.Id.decimal_separator;
			global::Acr.UserDialogs.Resource.Id.delete = global::Samples.Droid.Resource.Id.delete;
			global::Acr.UserDialogs.Resource.Id.divider = global::Samples.Droid.Resource.Id.divider;
			global::Acr.UserDialogs.Resource.Id.divider_1 = global::Samples.Droid.Resource.Id.divider_1;
			global::Acr.UserDialogs.Resource.Id.divider_2 = global::Samples.Droid.Resource.Id.divider_2;
			global::Acr.UserDialogs.Resource.Id.done = global::Samples.Droid.Resource.Id.done;
			global::Acr.UserDialogs.Resource.Id.done_button = global::Samples.Droid.Resource.Id.done_button;
			global::Acr.UserDialogs.Resource.Id.empty_item = global::Samples.Droid.Resource.Id.empty_item;
			global::Acr.UserDialogs.Resource.Id.endCount = global::Samples.Droid.Resource.Id.endCount;
			global::Acr.UserDialogs.Resource.Id.endDate = global::Samples.Droid.Resource.Id.endDate;
			global::Acr.UserDialogs.Resource.Id.endGroup = global::Samples.Droid.Resource.Id.endGroup;
			global::Acr.UserDialogs.Resource.Id.endSpinner = global::Samples.Droid.Resource.Id.endSpinner;
			global::Acr.UserDialogs.Resource.Id.error = global::Samples.Droid.Resource.Id.error;
			global::Acr.UserDialogs.Resource.Id.expiration_picker = global::Samples.Droid.Resource.Id.expiration_picker;
			global::Acr.UserDialogs.Resource.Id.expiration_seperator = global::Samples.Droid.Resource.Id.expiration_seperator;
			global::Acr.UserDialogs.Resource.Id.first = global::Samples.Droid.Resource.Id.first;
			global::Acr.UserDialogs.Resource.Id.fourth = global::Samples.Droid.Resource.Id.fourth;
			global::Acr.UserDialogs.Resource.Id.freqSpinner = global::Samples.Droid.Resource.Id.freqSpinner;
			global::Acr.UserDialogs.Resource.Id.header = global::Samples.Droid.Resource.Id.header;
			global::Acr.UserDialogs.Resource.Id.hms_picker = global::Samples.Droid.Resource.Id.hms_picker;
			global::Acr.UserDialogs.Resource.Id.hms_text = global::Samples.Droid.Resource.Id.hms_text;
			global::Acr.UserDialogs.Resource.Id.horizontal_scroll_view = global::Samples.Droid.Resource.Id.horizontal_scroll_view;
			global::Acr.UserDialogs.Resource.Id.hour_space = global::Samples.Droid.Resource.Id.hour_space;
			global::Acr.UserDialogs.Resource.Id.hours = global::Samples.Droid.Resource.Id.hours;
			global::Acr.UserDialogs.Resource.Id.hours_label = global::Samples.Droid.Resource.Id.hours_label;
			global::Acr.UserDialogs.Resource.Id.hours_ones = global::Samples.Droid.Resource.Id.hours_ones;
			global::Acr.UserDialogs.Resource.Id.hours_seperator = global::Samples.Droid.Resource.Id.hours_seperator;
			global::Acr.UserDialogs.Resource.Id.hours_tens = global::Samples.Droid.Resource.Id.hours_tens;
			global::Acr.UserDialogs.Resource.Id.interval = global::Samples.Droid.Resource.Id.interval;
			global::Acr.UserDialogs.Resource.Id.intervalGroup = global::Samples.Droid.Resource.Id.intervalGroup;
			global::Acr.UserDialogs.Resource.Id.intervalPostText = global::Samples.Droid.Resource.Id.intervalPostText;
			global::Acr.UserDialogs.Resource.Id.intervalPreText = global::Samples.Droid.Resource.Id.intervalPreText;
			global::Acr.UserDialogs.Resource.Id.key_left = global::Samples.Droid.Resource.Id.key_left;
			global::Acr.UserDialogs.Resource.Id.key_middle = global::Samples.Droid.Resource.Id.key_middle;
			global::Acr.UserDialogs.Resource.Id.key_right = global::Samples.Droid.Resource.Id.key_right;
			global::Acr.UserDialogs.Resource.Id.keyboard_indicator = global::Samples.Droid.Resource.Id.keyboard_indicator;
			global::Acr.UserDialogs.Resource.Id.keyboard_pager = global::Samples.Droid.Resource.Id.keyboard_pager;
			global::Acr.UserDialogs.Resource.Id.label = global::Samples.Droid.Resource.Id.label;
			global::Acr.UserDialogs.Resource.Id.line = global::Samples.Droid.Resource.Id.line;
			global::Acr.UserDialogs.Resource.Id.loadingImage = global::Samples.Droid.Resource.Id.loadingImage;
			global::Acr.UserDialogs.Resource.Id.loadingProgressBar = global::Samples.Droid.Resource.Id.loadingProgressBar;
			global::Acr.UserDialogs.Resource.Id.loadingProgressWheel = global::Samples.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.UserDialogs.Resource.Id.location = global::Samples.Droid.Resource.Id.location;
			global::Acr.UserDialogs.Resource.Id.minus_label = global::Samples.Droid.Resource.Id.minus_label;
			global::Acr.UserDialogs.Resource.Id.minutes = global::Samples.Droid.Resource.Id.minutes;
			global::Acr.UserDialogs.Resource.Id.minutes_label = global::Samples.Droid.Resource.Id.minutes_label;
			global::Acr.UserDialogs.Resource.Id.minutes_ones = global::Samples.Droid.Resource.Id.minutes_ones;
			global::Acr.UserDialogs.Resource.Id.minutes_space = global::Samples.Droid.Resource.Id.minutes_space;
			global::Acr.UserDialogs.Resource.Id.minutes_tens = global::Samples.Droid.Resource.Id.minutes_tens;
			global::Acr.UserDialogs.Resource.Id.month = global::Samples.Droid.Resource.Id.month;
			global::Acr.UserDialogs.Resource.Id.monthGroup = global::Samples.Droid.Resource.Id.monthGroup;
			global::Acr.UserDialogs.Resource.Id.month_text_view = global::Samples.Droid.Resource.Id.month_text_view;
			global::Acr.UserDialogs.Resource.Id.number = global::Samples.Droid.Resource.Id.number;
			global::Acr.UserDialogs.Resource.Id.number_picker = global::Samples.Droid.Resource.Id.number_picker;
			global::Acr.UserDialogs.Resource.Id.number_text = global::Samples.Droid.Resource.Id.number_text;
			global::Acr.UserDialogs.Resource.Id.number_view_container = global::Samples.Droid.Resource.Id.number_view_container;
			global::Acr.UserDialogs.Resource.Id.numbers_key = global::Samples.Droid.Resource.Id.numbers_key;
			global::Acr.UserDialogs.Resource.Id.options = global::Samples.Droid.Resource.Id.options;
			global::Acr.UserDialogs.Resource.Id.postEndCount = global::Samples.Droid.Resource.Id.postEndCount;
			global::Acr.UserDialogs.Resource.Id.repeatMonthlyByNthDayOfMonth = global::Samples.Droid.Resource.Id.repeatMonthlyByNthDayOfMonth;
			global::Acr.UserDialogs.Resource.Id.repeatMonthlyByNthDayOfTheWeek = global::Samples.Droid.Resource.Id.repeatMonthlyByNthDayOfTheWeek;
			global::Acr.UserDialogs.Resource.Id.repeat_switch = global::Samples.Droid.Resource.Id.repeat_switch;
			global::Acr.UserDialogs.Resource.Id.searchBox = global::Samples.Droid.Resource.Id.searchBox;
			global::Acr.UserDialogs.Resource.Id.second = global::Samples.Droid.Resource.Id.second;
			global::Acr.UserDialogs.Resource.Id.seconds_label = global::Samples.Droid.Resource.Id.seconds_label;
			global::Acr.UserDialogs.Resource.Id.seconds_ones = global::Samples.Droid.Resource.Id.seconds_ones;
			global::Acr.UserDialogs.Resource.Id.seconds_tens = global::Samples.Droid.Resource.Id.seconds_tens;
			global::Acr.UserDialogs.Resource.Id.separator = global::Samples.Droid.Resource.Id.separator;
			global::Acr.UserDialogs.Resource.Id.set_button = global::Samples.Droid.Resource.Id.set_button;
			global::Acr.UserDialogs.Resource.Id.spinner_item = global::Samples.Droid.Resource.Id.spinner_item;
			global::Acr.UserDialogs.Resource.Id.textViewStatus = global::Samples.Droid.Resource.Id.textViewStatus;
			global::Acr.UserDialogs.Resource.Id.third = global::Samples.Droid.Resource.Id.third;
			global::Acr.UserDialogs.Resource.Id.time_display = global::Samples.Droid.Resource.Id.time_display;
			global::Acr.UserDialogs.Resource.Id.time_display_background = global::Samples.Droid.Resource.Id.time_display_background;
			global::Acr.UserDialogs.Resource.Id.time_offset = global::Samples.Droid.Resource.Id.time_offset;
			global::Acr.UserDialogs.Resource.Id.time_picker = global::Samples.Droid.Resource.Id.time_picker;
			global::Acr.UserDialogs.Resource.Id.time_picker_dialog = global::Samples.Droid.Resource.Id.time_picker_dialog;
			global::Acr.UserDialogs.Resource.Id.time_zone = global::Samples.Droid.Resource.Id.time_zone;
			global::Acr.UserDialogs.Resource.Id.timer_time_text = global::Samples.Droid.Resource.Id.timer_time_text;
			global::Acr.UserDialogs.Resource.Id.timezonelist = global::Samples.Droid.Resource.Id.timezonelist;
			global::Acr.UserDialogs.Resource.Id.value = global::Samples.Droid.Resource.Id.value;
			global::Acr.UserDialogs.Resource.Id.weekGroup = global::Samples.Droid.Resource.Id.weekGroup;
			global::Acr.UserDialogs.Resource.Id.weekGroup2 = global::Samples.Droid.Resource.Id.weekGroup2;
			global::Acr.UserDialogs.Resource.Id.year_label = global::Samples.Droid.Resource.Id.year_label;
			global::Acr.UserDialogs.Resource.Layout.calendar_date_picker_dialog = global::Samples.Droid.Resource.Layout.calendar_date_picker_dialog;
			global::Acr.UserDialogs.Resource.Layout.calendar_date_picker_done_button = global::Samples.Droid.Resource.Layout.calendar_date_picker_done_button;
			global::Acr.UserDialogs.Resource.Layout.calendar_date_picker_header_view = global::Samples.Droid.Resource.Layout.calendar_date_picker_header_view;
			global::Acr.UserDialogs.Resource.Layout.calendar_date_picker_selected_date = global::Samples.Droid.Resource.Layout.calendar_date_picker_selected_date;
			global::Acr.UserDialogs.Resource.Layout.calendar_date_picker_view_animator = global::Samples.Droid.Resource.Layout.calendar_date_picker_view_animator;
			global::Acr.UserDialogs.Resource.Layout.calendar_year_label_text_view = global::Samples.Droid.Resource.Layout.calendar_year_label_text_view;
			global::Acr.UserDialogs.Resource.Layout.date_picker_dialog = global::Samples.Droid.Resource.Layout.date_picker_dialog;
			global::Acr.UserDialogs.Resource.Layout.date_picker_view = global::Samples.Droid.Resource.Layout.date_picker_view;
			global::Acr.UserDialogs.Resource.Layout.empty_time_zone_item = global::Samples.Droid.Resource.Layout.empty_time_zone_item;
			global::Acr.UserDialogs.Resource.Layout.expiration_picker_dialog = global::Samples.Droid.Resource.Layout.expiration_picker_dialog;
			global::Acr.UserDialogs.Resource.Layout.expiration_picker_view = global::Samples.Droid.Resource.Layout.expiration_picker_view;
			global::Acr.UserDialogs.Resource.Layout.hms_picker_dialog = global::Samples.Droid.Resource.Layout.hms_picker_dialog;
			global::Acr.UserDialogs.Resource.Layout.hms_picker_view = global::Samples.Droid.Resource.Layout.hms_picker_view;
			global::Acr.UserDialogs.Resource.Layout.keyboard = global::Samples.Droid.Resource.Layout.keyboard;
			global::Acr.UserDialogs.Resource.Layout.keyboard_right_drawable = global::Samples.Droid.Resource.Layout.keyboard_right_drawable;
			global::Acr.UserDialogs.Resource.Layout.keyboard_right_drawable_with_header = global::Samples.Droid.Resource.Layout.keyboard_right_drawable_with_header;
			global::Acr.UserDialogs.Resource.Layout.keyboard_text = global::Samples.Droid.Resource.Layout.keyboard_text;
			global::Acr.UserDialogs.Resource.Layout.keyboard_text_with_header = global::Samples.Droid.Resource.Layout.keyboard_text_with_header;
			global::Acr.UserDialogs.Resource.Layout.keyboard_with_header = global::Samples.Droid.Resource.Layout.keyboard_with_header;
			global::Acr.UserDialogs.Resource.Layout.loading = global::Samples.Droid.Resource.Layout.loading;
			global::Acr.UserDialogs.Resource.Layout.loadingimage = global::Samples.Droid.Resource.Layout.loadingimage;
			global::Acr.UserDialogs.Resource.Layout.loadingprogress = global::Samples.Droid.Resource.Layout.loadingprogress;
			global::Acr.UserDialogs.Resource.Layout.number_picker_dialog = global::Samples.Droid.Resource.Layout.number_picker_dialog;
			global::Acr.UserDialogs.Resource.Layout.number_picker_view = global::Samples.Droid.Resource.Layout.number_picker_view;
			global::Acr.UserDialogs.Resource.Layout.radial_time_header_label = global::Samples.Droid.Resource.Layout.radial_time_header_label;
			global::Acr.UserDialogs.Resource.Layout.radial_time_picker_dialog = global::Samples.Droid.Resource.Layout.radial_time_picker_dialog;
			global::Acr.UserDialogs.Resource.Layout.recurrencepicker = global::Samples.Droid.Resource.Layout.recurrencepicker;
			global::Acr.UserDialogs.Resource.Layout.recurrencepicker_end_text = global::Samples.Droid.Resource.Layout.recurrencepicker_end_text;
			global::Acr.UserDialogs.Resource.Layout.recurrencepicker_freq_item = global::Samples.Droid.Resource.Layout.recurrencepicker_freq_item;
			global::Acr.UserDialogs.Resource.Layout.three_keys_view = global::Samples.Droid.Resource.Layout.three_keys_view;
			global::Acr.UserDialogs.Resource.Layout.three_keys_view_leftright = global::Samples.Droid.Resource.Layout.three_keys_view_leftright;
			global::Acr.UserDialogs.Resource.Layout.three_keys_view_right_drawable = global::Samples.Droid.Resource.Layout.three_keys_view_right_drawable;
			global::Acr.UserDialogs.Resource.Layout.three_keys_view_text = global::Samples.Droid.Resource.Layout.three_keys_view_text;
			global::Acr.UserDialogs.Resource.Layout.time_picker_dialog = global::Samples.Droid.Resource.Layout.time_picker_dialog;
			global::Acr.UserDialogs.Resource.Layout.time_picker_view = global::Samples.Droid.Resource.Layout.time_picker_view;
			global::Acr.UserDialogs.Resource.Layout.time_zone_filter_item = global::Samples.Droid.Resource.Layout.time_zone_filter_item;
			global::Acr.UserDialogs.Resource.Layout.time_zone_item = global::Samples.Droid.Resource.Layout.time_zone_item;
			global::Acr.UserDialogs.Resource.Layout.timezonepickerview = global::Samples.Droid.Resource.Layout.timezonepickerview;
			global::Acr.UserDialogs.Resource.Plurals.daily = global::Samples.Droid.Resource.Plurals.daily;
			global::Acr.UserDialogs.Resource.Plurals.endByCount = global::Samples.Droid.Resource.Plurals.endByCount;
			global::Acr.UserDialogs.Resource.Plurals.recurrence_end_count = global::Samples.Droid.Resource.Plurals.recurrence_end_count;
			global::Acr.UserDialogs.Resource.Plurals.recurrence_interval_daily = global::Samples.Droid.Resource.Plurals.recurrence_interval_daily;
			global::Acr.UserDialogs.Resource.Plurals.recurrence_interval_monthly = global::Samples.Droid.Resource.Plurals.recurrence_interval_monthly;
			global::Acr.UserDialogs.Resource.Plurals.recurrence_interval_weekly = global::Samples.Droid.Resource.Plurals.recurrence_interval_weekly;
			global::Acr.UserDialogs.Resource.Plurals.recurrence_interval_yearly = global::Samples.Droid.Resource.Plurals.recurrence_interval_yearly;
			global::Acr.UserDialogs.Resource.Plurals.weekly = global::Samples.Droid.Resource.Plurals.weekly;
			global::Acr.UserDialogs.Resource.String.ApplicationName = global::Samples.Droid.Resource.String.ApplicationName;
			global::Acr.UserDialogs.Resource.String.Hello = global::Samples.Droid.Resource.String.Hello;
			global::Acr.UserDialogs.Resource.String.acessibility_recurrence_choose_end_date_description = global::Samples.Droid.Resource.String.acessibility_recurrence_choose_end_date_description;
			global::Acr.UserDialogs.Resource.String.ampm_circle_radius_multiplier = global::Samples.Droid.Resource.String.ampm_circle_radius_multiplier;
			global::Acr.UserDialogs.Resource.String.circle_radius_multiplier = global::Samples.Droid.Resource.String.circle_radius_multiplier;
			global::Acr.UserDialogs.Resource.String.circle_radius_multiplier_24HourMode = global::Samples.Droid.Resource.String.circle_radius_multiplier_24HourMode;
			global::Acr.UserDialogs.Resource.String.day_c = global::Samples.Droid.Resource.String.day_c;
			global::Acr.UserDialogs.Resource.String.day_of_week_label_typeface = global::Samples.Droid.Resource.String.day_of_week_label_typeface;
			global::Acr.UserDialogs.Resource.String.day_picker_description = global::Samples.Droid.Resource.String.day_picker_description;
			global::Acr.UserDialogs.Resource.String.deleted_key = global::Samples.Droid.Resource.String.deleted_key;
			global::Acr.UserDialogs.Resource.String.done_label = global::Samples.Droid.Resource.String.done_label;
			global::Acr.UserDialogs.Resource.String.endByDate = global::Samples.Droid.Resource.String.endByDate;
			global::Acr.UserDialogs.Resource.String.every_weekday = global::Samples.Droid.Resource.String.every_weekday;
			global::Acr.UserDialogs.Resource.String.expiration_picker_seperator = global::Samples.Droid.Resource.String.expiration_picker_seperator;
			global::Acr.UserDialogs.Resource.String.hint_time_zone_search = global::Samples.Droid.Resource.String.hint_time_zone_search;
			global::Acr.UserDialogs.Resource.String.hms_picker_hours_label = global::Samples.Droid.Resource.String.hms_picker_hours_label;
			global::Acr.UserDialogs.Resource.String.hms_picker_minutes_label = global::Samples.Droid.Resource.String.hms_picker_minutes_label;
			global::Acr.UserDialogs.Resource.String.hms_picker_seconds_label = global::Samples.Droid.Resource.String.hms_picker_seconds_label;
			global::Acr.UserDialogs.Resource.String.hour_picker_description = global::Samples.Droid.Resource.String.hour_picker_description;
			global::Acr.UserDialogs.Resource.String.hours_label = global::Samples.Droid.Resource.String.hours_label;
			global::Acr.UserDialogs.Resource.String.hours_label_description = global::Samples.Droid.Resource.String.hours_label_description;
			global::Acr.UserDialogs.Resource.String.item_is_selected = global::Samples.Droid.Resource.String.item_is_selected;
			global::Acr.UserDialogs.Resource.String.library_name = global::Samples.Droid.Resource.String.library_name;
			global::Acr.UserDialogs.Resource.String.max_error = global::Samples.Droid.Resource.String.max_error;
			global::Acr.UserDialogs.Resource.String.min_error = global::Samples.Droid.Resource.String.min_error;
			global::Acr.UserDialogs.Resource.String.min_max_error = global::Samples.Droid.Resource.String.min_max_error;
			global::Acr.UserDialogs.Resource.String.minute_picker_description = global::Samples.Droid.Resource.String.minute_picker_description;
			global::Acr.UserDialogs.Resource.String.minutes_label = global::Samples.Droid.Resource.String.minutes_label;
			global::Acr.UserDialogs.Resource.String.minutes_label_description = global::Samples.Droid.Resource.String.minutes_label_description;
			global::Acr.UserDialogs.Resource.String.month_c = global::Samples.Droid.Resource.String.month_c;
			global::Acr.UserDialogs.Resource.String.monthly = global::Samples.Droid.Resource.String.monthly;
			global::Acr.UserDialogs.Resource.String.no_results_found = global::Samples.Droid.Resource.String.no_results_found;
			global::Acr.UserDialogs.Resource.String.number_delete = global::Samples.Droid.Resource.String.number_delete;
			global::Acr.UserDialogs.Resource.String.number_picker_minus_label = global::Samples.Droid.Resource.String.number_picker_minus_label;
			global::Acr.UserDialogs.Resource.String.number_picker_plus_minus = global::Samples.Droid.Resource.String.number_picker_plus_minus;
			global::Acr.UserDialogs.Resource.String.number_picker_seperator = global::Samples.Droid.Resource.String.number_picker_seperator;
			global::Acr.UserDialogs.Resource.String.numbers_radius_multiplier_inner = global::Samples.Droid.Resource.String.numbers_radius_multiplier_inner;
			global::Acr.UserDialogs.Resource.String.numbers_radius_multiplier_normal = global::Samples.Droid.Resource.String.numbers_radius_multiplier_normal;
			global::Acr.UserDialogs.Resource.String.numbers_radius_multiplier_outer = global::Samples.Droid.Resource.String.numbers_radius_multiplier_outer;
			global::Acr.UserDialogs.Resource.String.palestine_display_name = global::Samples.Droid.Resource.String.palestine_display_name;
			global::Acr.UserDialogs.Resource.String.picker_cancel = global::Samples.Droid.Resource.String.picker_cancel;
			global::Acr.UserDialogs.Resource.String.picker_set = global::Samples.Droid.Resource.String.picker_set;
			global::Acr.UserDialogs.Resource.String.radial_numbers_typeface = global::Samples.Droid.Resource.String.radial_numbers_typeface;
			global::Acr.UserDialogs.Resource.String.recurrence_end_continously = global::Samples.Droid.Resource.String.recurrence_end_continously;
			global::Acr.UserDialogs.Resource.String.recurrence_end_count_label = global::Samples.Droid.Resource.String.recurrence_end_count_label;
			global::Acr.UserDialogs.Resource.String.recurrence_end_date = global::Samples.Droid.Resource.String.recurrence_end_date;
			global::Acr.UserDialogs.Resource.String.recurrence_end_date_label = global::Samples.Droid.Resource.String.recurrence_end_date_label;
			global::Acr.UserDialogs.Resource.String.recurrence_month_pattern_by_day = global::Samples.Droid.Resource.String.recurrence_month_pattern_by_day;
			global::Acr.UserDialogs.Resource.String.sans_serif = global::Samples.Droid.Resource.String.sans_serif;
			global::Acr.UserDialogs.Resource.String.save_label = global::Samples.Droid.Resource.String.save_label;
			global::Acr.UserDialogs.Resource.String.searchview_description_clear = global::Samples.Droid.Resource.String.searchview_description_clear;
			global::Acr.UserDialogs.Resource.String.seconds_label = global::Samples.Droid.Resource.String.seconds_label;
			global::Acr.UserDialogs.Resource.String.seconds_label_description = global::Samples.Droid.Resource.String.seconds_label_description;
			global::Acr.UserDialogs.Resource.String.select_day = global::Samples.Droid.Resource.String.select_day;
			global::Acr.UserDialogs.Resource.String.select_hours = global::Samples.Droid.Resource.String.select_hours;
			global::Acr.UserDialogs.Resource.String.select_minutes = global::Samples.Droid.Resource.String.select_minutes;
			global::Acr.UserDialogs.Resource.String.select_year = global::Samples.Droid.Resource.String.select_year;
			global::Acr.UserDialogs.Resource.String.selection_radius_multiplier = global::Samples.Droid.Resource.String.selection_radius_multiplier;
			global::Acr.UserDialogs.Resource.String.switch_off = global::Samples.Droid.Resource.String.switch_off;
			global::Acr.UserDialogs.Resource.String.switch_on = global::Samples.Droid.Resource.String.switch_on;
			global::Acr.UserDialogs.Resource.String.text_size_multiplier_inner = global::Samples.Droid.Resource.String.text_size_multiplier_inner;
			global::Acr.UserDialogs.Resource.String.text_size_multiplier_normal = global::Samples.Droid.Resource.String.text_size_multiplier_normal;
			global::Acr.UserDialogs.Resource.String.text_size_multiplier_outer = global::Samples.Droid.Resource.String.text_size_multiplier_outer;
			global::Acr.UserDialogs.Resource.String.time_picker_00_label = global::Samples.Droid.Resource.String.time_picker_00_label;
			global::Acr.UserDialogs.Resource.String.time_picker_30_label = global::Samples.Droid.Resource.String.time_picker_30_label;
			global::Acr.UserDialogs.Resource.String.time_picker_ampm_label = global::Samples.Droid.Resource.String.time_picker_ampm_label;
			global::Acr.UserDialogs.Resource.String.time_picker_time_seperator = global::Samples.Droid.Resource.String.time_picker_time_seperator;
			global::Acr.UserDialogs.Resource.String.time_placeholder = global::Samples.Droid.Resource.String.time_placeholder;
			global::Acr.UserDialogs.Resource.String.time_separator = global::Samples.Droid.Resource.String.time_separator;
			global::Acr.UserDialogs.Resource.String.timer_delete = global::Samples.Droid.Resource.String.timer_delete;
			global::Acr.UserDialogs.Resource.String.year_c = global::Samples.Droid.Resource.String.year_c;
			global::Acr.UserDialogs.Resource.String.year_picker_description = global::Samples.Droid.Resource.String.year_picker_description;
			global::Acr.UserDialogs.Resource.String.yearly_plain = global::Samples.Droid.Resource.String.yearly_plain;
			global::Acr.UserDialogs.Resource.Style.BetterPickersDialogFragment = global::Samples.Droid.Resource.Style.BetterPickersDialogFragment;
			global::Acr.UserDialogs.Resource.Style.BetterPickersDialogFragment_Light = global::Samples.Droid.Resource.Style.BetterPickersDialogFragment_Light;
			global::Acr.UserDialogs.Resource.Style.RecurrenceDayOfWeekStyle = global::Samples.Droid.Resource.Style.RecurrenceDayOfWeekStyle;
			global::Acr.UserDialogs.Resource.Style.TextAppearance_EditEvent_Spinner = global::Samples.Droid.Resource.Style.TextAppearance_EditEvent_Spinner;
			global::Acr.UserDialogs.Resource.Style.TextAppearance_EditEvent_SpinnerButton = global::Samples.Droid.Resource.Style.TextAppearance_EditEvent_SpinnerButton;
			global::Acr.UserDialogs.Resource.Style.TextAppearance_Holo_Light_Widget_Switch = global::Samples.Droid.Resource.Style.TextAppearance_Holo_Light_Widget_Switch;
			global::Acr.UserDialogs.Resource.Style.TextAppearance_RecurrencePickerStyle = global::Samples.Droid.Resource.Style.TextAppearance_RecurrencePickerStyle;
			global::Acr.UserDialogs.Resource.Style.Widget_Holo_Light_CompoundButton_Switch = global::Samples.Droid.Resource.Style.Widget_Holo_Light_CompoundButton_Switch;
			global::Acr.UserDialogs.Resource.Style.aosp_ampm_label = global::Samples.Droid.Resource.Style.aosp_ampm_label;
			global::Acr.UserDialogs.Resource.Style.aosp_day_of_week_label_condensed = global::Samples.Droid.Resource.Style.aosp_day_of_week_label_condensed;
			global::Acr.UserDialogs.Resource.Style.aosp_time_label = global::Samples.Droid.Resource.Style.aosp_time_label;
			global::Acr.UserDialogs.Resource.Style.dialog_button = global::Samples.Droid.Resource.Style.dialog_button;
			global::Acr.UserDialogs.Resource.Style.dialpad = global::Samples.Droid.Resource.Style.dialpad;
			global::Acr.UserDialogs.Resource.Style.dialpad_text = global::Samples.Droid.Resource.Style.dialpad_text;
			global::Acr.UserDialogs.Resource.Style.label = global::Samples.Droid.Resource.Style.label;
			global::Acr.UserDialogs.Resource.Style.medium_bold = global::Samples.Droid.Resource.Style.medium_bold;
			global::Acr.UserDialogs.Resource.Style.medium_bold_date = global::Samples.Droid.Resource.Style.medium_bold_date;
			global::Acr.UserDialogs.Resource.Style.medium_bold_hms = global::Samples.Droid.Resource.Style.medium_bold_hms;
			global::Acr.UserDialogs.Resource.Style.medium_light = global::Samples.Droid.Resource.Style.medium_light;
			global::Acr.UserDialogs.Resource.Style.medium_light_date = global::Samples.Droid.Resource.Style.medium_light_date;
			global::Acr.UserDialogs.Resource.Style.medium_light_expiration = global::Samples.Droid.Resource.Style.medium_light_expiration;
			global::Acr.UserDialogs.Resource.Style.medium_light_header = global::Samples.Droid.Resource.Style.medium_light_header;
			global::Acr.UserDialogs.Resource.Style.medium_light_hms = global::Samples.Droid.Resource.Style.medium_light_hms;
			global::Acr.UserDialogs.Resource.Style.tablet_dialpad = global::Samples.Droid.Resource.Style.tablet_dialpad;
			global::Acr.UserDialogs.Resource.Style.tablet_dialpad_text = global::Samples.Droid.Resource.Style.tablet_dialpad_text;
			global::Acr.UserDialogs.Resource.Styleable.Android = global::Samples.Droid.Resource.Styleable.Android;
			global::Acr.UserDialogs.Resource.Styleable.Android_android_textColor = global::Samples.Droid.Resource.Styleable.Android_android_textColor;
			global::Acr.UserDialogs.Resource.Styleable.Android_android_textColorHighlight = global::Samples.Droid.Resource.Styleable.Android_android_textColorHighlight;
			global::Acr.UserDialogs.Resource.Styleable.Android_android_textColorHint = global::Samples.Droid.Resource.Styleable.Android_android_textColorHint;
			global::Acr.UserDialogs.Resource.Styleable.Android_android_textColorLink = global::Samples.Droid.Resource.Styleable.Android_android_textColorLink;
			global::Acr.UserDialogs.Resource.Styleable.Android_android_textSize = global::Samples.Droid.Resource.Styleable.Android_android_textSize;
			global::Acr.UserDialogs.Resource.Styleable.Android_android_textStyle = global::Samples.Droid.Resource.Styleable.Android_android_textStyle;
			global::Acr.UserDialogs.Resource.Styleable.Android_android_typeface = global::Samples.Droid.Resource.Styleable.Android_android_typeface;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpButtonBackground = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpButtonBackground;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpCheckIcon = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpCheckIcon;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpDeleteIcon = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpDeleteIcon;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpDialogBackground = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpDialogBackground;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpDividerColor = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpDividerColor;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpKeyBackground = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpKeyBackground;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpKeyboardIndicatorColor = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpKeyboardIndicatorColor;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpTextColor = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpTextColor;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpTitleColor = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpTitleColor;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersDialogFragment_bpTitleDividerColor = global::Samples.Droid.Resource.Styleable.BetterPickersDialogFragment_bpTitleDividerColor;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersSwitchTheme = global::Samples.Droid.Resource.Styleable.BetterPickersSwitchTheme;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersSwitchTheme_switchPreferenceStyle = global::Samples.Droid.Resource.Styleable.BetterPickersSwitchTheme_switchPreferenceStyle;
			global::Acr.UserDialogs.Resource.Styleable.BetterPickersSwitchTheme_switchStyle = global::Samples.Droid.Resource.Styleable.BetterPickersSwitchTheme_switchStyle;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel = global::Samples.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarColor = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarLength = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahBarWidth = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahCircleColor = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRadius = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimColor = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahRimWidth = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahText = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextColor = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.UserDialogs.Resource.Styleable.ProgressWheel_ahTextSize = global::Samples.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::Acr.UserDialogs.Resource.Styleable.Switch = global::Samples.Droid.Resource.Styleable.Switch;
			global::Acr.UserDialogs.Resource.Styleable.Switch_switchMinWidth = global::Samples.Droid.Resource.Styleable.Switch_switchMinWidth;
			global::Acr.UserDialogs.Resource.Styleable.Switch_switchPadding = global::Samples.Droid.Resource.Styleable.Switch_switchPadding;
			global::Acr.UserDialogs.Resource.Styleable.Switch_switchTextAppearance = global::Samples.Droid.Resource.Styleable.Switch_switchTextAppearance;
			global::Acr.UserDialogs.Resource.Styleable.Switch_textOff = global::Samples.Droid.Resource.Styleable.Switch_textOff;
			global::Acr.UserDialogs.Resource.Styleable.Switch_textOn = global::Samples.Droid.Resource.Styleable.Switch_textOn;
			global::Acr.UserDialogs.Resource.Styleable.Switch_thumb = global::Samples.Droid.Resource.Styleable.Switch_thumb;
			global::Acr.UserDialogs.Resource.Styleable.Switch_thumbTextPadding = global::Samples.Droid.Resource.Styleable.Switch_thumbTextPadding;
			global::Acr.UserDialogs.Resource.Styleable.Switch_track = global::Samples.Droid.Resource.Styleable.Switch_track;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
