<Project>
    <PropertyGroup>
        <Authors>Allan Ritchie</Authors>
        <PackageProjectUrl>https://github.com/aritchie/userdialogs</PackageProjectUrl>
        <Description>A cross platform library that allows you to call for standard user dialogs like Alerts, Confirmations, Prompts, and more. Supports Android, iOS, and MacCatalyst</Description>
        <PackageTags>ios android xamarin xam.pcl dialogs plugin maui uno userdialogs</PackageTags>
        <PackageReleaseNotes>https://github.com/aritchie/userdialogs/raw/master/ChangeLog.md</PackageReleaseNotes>
        <PackageIconUrl>https://github.com/aritchie/userdialogs/raw/master/icon.png</PackageIconUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <LangVersion>latest</LangVersion>
        <NoWarn>$(NoWarn);1591;1701;1591;1702;1705;VSX1000;NU1603</NoWarn>
        <RepositoryUrl>https://github.com/aritchie/userdialogs</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PlatformTargetFrameworks>net8.0;net8.0-ios18.0;net8.0-maccatalyst18.0;net8.0-android34.0</PlatformTargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <IncludeSource>True</IncludeSource>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>True</PublishRepositoryUrl>
        <EmbedUntrackedSources>True</EmbedUntrackedSources>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true' OR '$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>
  
    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.7.115">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>